export const RES_TRANSFORM = 'RES_TRANSFORM'

export const ROUTE_METEDATA = 'ROUTE_METEDATA'

export const JWT_AUTH = 'JWT_AUTH'

export const OPERATE_LOG = 'OPERATE_LOG'

export const OPERATE_LOG_OPTIONS = 'OPERATE_LOG_OPTIONS'

export const RES_CACHE = 'RES_CACHE_KEY'

export const RES_CACHE_OPTIONS = 'RES_CACHE_OPTIONS'
